# This is a basic workflow to help you get started with Actions
name: ci
# Controls when the action will run
on: 
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build":
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node environment
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      # Install dependencies
      - name: Install dependencies
        run: yarn install

      # Run lint
      - name: Linting
        run: yarn lint

      # Run tests
      - name: Test
        run: yarn test

      # Run build
      - name: Build
        run: yarn build
